# Generated by Django 2.2.19 on 2021-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTestInstanceInfo',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务实例id')),
                ('session_id', models.CharField(max_length=36, null=True)),
                ('offer_id', models.CharField(max_length=64, verbose_name='资费id')),
                ('start_time', models.CharField(max_length=19, verbose_name='任务开始时间')),
                ('end_time', models.CharField(max_length=19, verbose_name='任务结束时间')),
                ('test_people', models.CharField(max_length=19, verbose_name='测试人员')),
                ('product_name', models.CharField(max_length=128, verbose_name='所属产品线')),
            ],
            options={
                'verbose_name': '测试实例信息表',
                'db_table': 't_test_instance_info',
            },
        ),
        migrations.CreateModel(
            name='TTestRequireInfo',
            fields=[
                ('require_id', models.AutoField(primary_key=True, serialize=False)),
                ('require_name', models.CharField(max_length=64, verbose_name='测试名称')),
                ('offer_id', models.CharField(max_length=64, null=True)),
                ('offer_name', models.CharField(max_length=256, null=True)),
                ('require_source', models.CharField(max_length=64, verbose_name='产品线名称')),
                ('test_claim', models.CharField(max_length=256, verbose_name='测试人员')),
                ('test_date', models.CharField(max_length=19, verbose_name='测试时间')),
                ('test_status', models.CharField(max_length=16, verbose_name='测试状态')),
            ],
            options={
                'verbose_name': '测试结果信息表',
                'db_table': 't_test_require_info',
            },
        ),
        migrations.CreateModel(
            name='TTestTaskInfo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=255)),
                ('begin_time', models.CharField(max_length=19)),
                ('end_time', models.CharField(max_length=19)),
                ('case_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '测试任务信息表',
                'db_table': 't_test_task_info',
            },
        ),
    ]
