# Generated by Django 2.2.19 on 2021-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole_process_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttestrequireinfo',
            name='require_file_desc',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
