# Generated by Django 2.2.19 on 2021-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole_process_test', '0002_ttestrequireinfo_require_file_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TResultFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('file_type', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '获取测试结果文件信息',
                'db_table': 't_test_result_file_info',
            },
        ),
        migrations.AlterField(
            model_name='ttestinstanceinfo',
            name='offer_id',
            field=models.CharField(max_length=64, verbose_name='产品名称'),
        ),
    ]
