# Generated by Django 2.2.19 on 2021-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(default='', help_text='菜单目录id', max_length=10, verbose_name='菜单目录id')),
                ('menu_level', models.IntegerField(choices=[(1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], help_text='菜单目录级别', verbose_name='菜单目录级别')),
                ('menu_name', models.CharField(default='', help_text='菜单名称', max_length=10, verbose_name='菜单名称')),
                ('parent_menu_id', models.CharField(default='', help_text='菜单父目录id', max_length=10, verbose_name='菜单父目录id')),
                ('menu_url', models.CharField(default='', help_text='菜单路由', max_length=256, verbose_name='菜单路由')),
            ],
            options={
                'verbose_name': '菜单信息',
                'verbose_name_plural': '菜单信息',
                'db_table': 't_test_menu_info',
            },
        ),
        migrations.CreateModel(
            name='RoleAuthorityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(default='', help_text='角色id', max_length=10, verbose_name='角色id')),
                ('role_name', models.CharField(default='', help_text='角色名称', max_length=20, verbose_name='角色名称')),
                ('role_desc', models.CharField(default='', help_text='角色描述', max_length=200, verbose_name='角色描述')),
                ('menu_id', models.CharField(default='', help_text='菜单目录id', max_length=10, verbose_name='菜单目录id')),
            ],
            options={
                'verbose_name': '角色权限信息表',
                'verbose_name_plural': '角色权限信息表',
                'db_table': 't_test_role_authority_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=256, verbose_name='密码')),
                ('role_id', models.CharField(default='', help_text='角色id', max_length=10, verbose_name='角色id')),
                ('product_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品线名称')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 't_test_user_info',
            },
        ),
    ]
