# Generated by Django 2.2.19 on 2021-03-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, help_text='登录token', max_length=256, null=True, verbose_name='登录token'),
        ),
    ]
