# Generated by Django 2.2.19 on 2021-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='current_branch',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户所属分支'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='product_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='分支产品线名称'),
        ),
    ]
