# Generated by Django 2.2.19 on 2021-03-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210313_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role_id',
            field=models.CharField(blank=True, help_text='角色id', max_length=10, null=True, verbose_name='角色id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
    ]
