# Generated by Django 2.2.19 on 2021-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210314_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
