# Generated by Django 2.2.19 on 2021-03-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCaseBindPointInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(blank=True, help_text='测试用例id', null=True, verbose_name='测试用例id')),
                ('point_id', models.IntegerField(blank=True, help_text='测试点id', null=True, verbose_name='测试点id')),
            ],
            options={
                'verbose_name': '测试用例绑定测试点桥表',
                'verbose_name_plural': '测试用例绑定测试点桥表',
                'db_table': 't_case_bind_point_info',
            },
        ),
        migrations.CreateModel(
            name='TCaseTemplateInfo',
            fields=[
                ('case_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, help_text='模板名称', max_length=255, null=True, verbose_name='模板名称')),
                ('module_type', models.CharField(blank=True, help_text='模板类型', max_length=255, null=True, verbose_name='模板类型')),
                ('regular_type', models.IntegerField(blank=True, null=True)),
                ('regular_type_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='生效状态', max_length=255, null=True, verbose_name='生效状态')),
                ('eff_time', models.CharField(blank=True, help_text='生效时间', max_length=19, null=True, verbose_name='生效时间')),
                ('exp_time', models.CharField(blank=True, help_text='失效时间', max_length=19, null=True, verbose_name='失效时间')),
                ('create_time', models.CharField(blank=True, help_text='创建时间', max_length=19, null=True, verbose_name='创建时间')),
                ('author', models.CharField(blank=True, help_text='创建用户', max_length=255, null=True, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '模板绑定用例信息表',
                'verbose_name_plural': '模板绑定用例信息表',
                'db_table': 't_case_template_info',
            },
        ),
        migrations.CreateModel(
            name='TemplateBindCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_template_id', models.IntegerField(blank=True, help_text='测试模板id', null=True, verbose_name='测试模板id')),
                ('case_id', models.IntegerField(blank=True, help_text='测试用例id', null=True, verbose_name='测试用例id')),
            ],
            options={
                'verbose_name': '测试用例绑定模板桥表',
                'verbose_name_plural': '测试用例绑定模板桥表',
                'db_table': 't_template_bind_case_info',
            },
        ),
        migrations.CreateModel(
            name='TTemplateBindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_id', models.IntegerField(help_text='测试需求id', verbose_name='测试需求id')),
                ('template_id', models.IntegerField(help_text='模板id', verbose_name='模板id')),
            ],
            options={
                'verbose_name': '测试需求绑定模板表',
                'verbose_name_plural': '测试需求绑定模板表',
                'db_table': 't_template_bind_info',
            },
        ),
        migrations.CreateModel(
            name='TTestCaseInfo',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用例id')),
                ('case_name', models.CharField(blank=True, help_text='用例名称', max_length=255, null=True, verbose_name='用例名称')),
                ('case_type', models.CharField(blank=True, help_text='用例类型', max_length=255, null=True, verbose_name='用例类型')),
                ('test_process', models.CharField(blank=True, help_text='测试流程', max_length=255, null=True, verbose_name='测试流程')),
                ('preset_data', models.CharField(blank=True, help_text='预置数据', max_length=255, null=True, verbose_name='预置数据')),
                ('input_data', models.CharField(blank=True, help_text='结果数据', max_length=255, null=True, verbose_name='结果数据')),
                ('test_action', models.CharField(blank=True, help_text='用例所属产品线', max_length=255, null=True, verbose_name='用例所属产品线')),
                ('point_type', models.CharField(blank=True, help_text='测试点类型', max_length=255, null=True, verbose_name='测试点类型')),
                ('eff_time', models.CharField(blank=True, help_text='生效时间', max_length=19, null=True, verbose_name='生效时间')),
                ('exp_time', models.CharField(blank=True, help_text='失效时间', max_length=19, null=True, verbose_name='失效时间')),
                ('create_time', models.CharField(blank=True, help_text='创建时间', max_length=19, null=True, verbose_name='创建时间')),
                ('author', models.CharField(blank=True, help_text='创建者', max_length=255, null=True, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
                'db_table': 't_test_case_info',
            },
        ),
        migrations.CreateModel(
            name='TTestCheckIsfocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_code', models.CharField(blank=True, help_text='省份代码', max_length=255, null=True, verbose_name='省份代码')),
                ('offer_id', models.CharField(blank=True, help_text='需求id', max_length=255, null=True, verbose_name='需求id')),
                ('batch', models.IntegerField(blank=True, help_text='测试批次', null=True, verbose_name='测试批次')),
                ('check_desc', models.CharField(blank=True, help_text='确认描述', max_length=255, null=True, verbose_name='确认描述')),
                ('session_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'verbose_name': '确认测试结果表',
                'verbose_name_plural': '确认测试结果表',
                'db_table': 't_test_check_isfocus',
            },
        ),
        migrations.CreateModel(
            name='TTestDockerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(blank=True, help_text='容器名称', max_length=64, null=True, verbose_name='容器名称')),
                ('exec_scripts', models.CharField(blank=True, help_text='执行命令脚本', max_length=255, null=True, verbose_name='执行命令脚本')),
                ('product_name', models.CharField(blank=True, help_text='产品名称', max_length=255, null=True, verbose_name='产品名称')),
                ('program_dir', models.CharField(blank=True, help_text='容器代码目录', max_length=255, null=True, verbose_name='容器代码目录')),
                ('local_program_dir', models.CharField(blank=True, help_text='主机代码目录', max_length=255, null=True, verbose_name='主机代码目录')),
                ('result_log_dir', models.CharField(blank=True, help_text='容器结果目录', max_length=255, null=True, verbose_name='容器结果目录')),
                ('local_log_dir', models.CharField(blank=True, help_text='主机结果目录', max_length=255, null=True, verbose_name='主机结果目录')),
                ('svn_dir', models.CharField(blank=True, help_text='svn路径', max_length=255, null=True, verbose_name='svn路径')),
                ('git_dir', models.CharField(blank=True, help_text='git路径', max_length=255, null=True, verbose_name='git路径')),
                ('git_branch_name', models.CharField(blank=True, help_text='git分支', max_length=64, null=True, verbose_name='git分支')),
                ('vcs_type', models.CharField(blank=True, help_text='代码版本控制类型', max_length=64, null=True, verbose_name='代码版本控制类型')),
                ('mark', models.CharField(blank=True, help_text='说明', max_length=255, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'pytest单元全流程测试容器管理表',
                'verbose_name_plural': 'pytest单元全流程测试容器管理表',
                'db_table': 't_test_docker_info',
            },
        ),
        migrations.CreateModel(
            name='TTestHostDataInfo',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_ip', models.CharField(blank=True, help_text='测试主机ip', max_length=20, null=True, verbose_name='测试主机ip')),
                ('host_user', models.CharField(blank=True, help_text='登录用户', max_length=20, null=True, verbose_name='登录用户')),
                ('host_pwd', models.CharField(blank=True, help_text='登录密码', max_length=128, null=True, verbose_name='登录密码')),
                ('host_path', models.CharField(blank=True, help_text='主机路径', max_length=128, null=True, verbose_name='主机路径')),
                ('exec_env', models.CharField(blank=True, help_text='主机环境类型', max_length=20, null=True, verbose_name='主机环境类型')),
                ('is_cur_env', models.CharField(blank=True, help_text='当前主机测试', max_length=10, null=True, verbose_name='当前主机测试')),
                ('product_name', models.CharField(blank=True, help_text='产品名称', max_length=128, null=True, verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '测试主机管理表',
                'verbose_name_plural': '测试主机管理表',
                'db_table': 't_test_host_data_info',
            },
        ),
        migrations.CreateModel(
            name='TTestPointInfo',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('point_code', models.CharField(blank=True, help_text='测试点编码', max_length=255, null=True, verbose_name='测试点编码')),
                ('point_type', models.CharField(blank=True, help_text='测试点类型', max_length=255, null=True, verbose_name='测试点类型')),
                ('point_name', models.CharField(blank=True, help_text='测试点名称', max_length=255, null=True, verbose_name='测试点名称')),
                ('point_desc', models.CharField(blank=True, help_text='测试点描述', max_length=255, null=True, verbose_name='测试点描述')),
                ('point_regular', models.CharField(blank=True, max_length=255, null=True)),
                ('expect_result', models.CharField(blank=True, help_text='测试点预期结果', max_length=255, null=True, verbose_name='测试点预期结果')),
            ],
            options={
                'verbose_name': '测试点表',
                'verbose_name_plural': '测试点表',
                'db_table': 't_test_point_info',
            },
        ),
    ]
