# Generated by Django 2.2.19 on 2021-03-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTestOperateDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='产品名称', max_length=128, verbose_name='产品名称')),
                ('operate_month', models.CharField(help_text='数据所属月份', max_length=10, verbose_name='数据所属月份')),
                ('prov_name', models.CharField(help_text='省份类型', max_length=64, verbose_name='运营省份')),
                ('prov_type', models.IntegerField(choices=[(1, 'PaaS产品'), (2, 'SaaS产品')], help_text='省份类型', verbose_name='省份类型')),
                ('operative_index', models.CharField(help_text='展示参数名称', max_length=64, verbose_name='展示参数名称')),
                ('operative_sub_index', models.CharField(blank=True, help_text='展示子参数名称', max_length=128, null=True, verbose_name='展示子参数名称')),
                ('operate_desc', models.CharField(blank=True, help_text='展示子参数描述', max_length=256, null=True, verbose_name='展示子参数描述')),
                ('operate_data', models.CharField(help_text='展示子参数值', max_length=64, verbose_name='展示子参数值')),
                ('show_flag', models.CharField(blank=True, help_text='是否展示', max_length=5, null=True, verbose_name='是否展示')),
                ('units', models.CharField(blank=True, help_text='子参数单位', max_length=10, null=True, verbose_name='子参数单位')),
                ('product_ver', models.CharField(blank=True, help_text='产品版本号', max_length=256, null=True, verbose_name='产品版本号')),
                ('target_value', models.CharField(blank=True, help_text='当月目标值', max_length=20, null=True, verbose_name='当月目标值')),
            ],
            options={
                'verbose_name': '运营数据配置信息表',
                'verbose_name_plural': '运营数据配置信息表',
                'db_table': 't_test_operate_data_info',
            },
        ),
        migrations.CreateModel(
            name='TTestOperateViewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='产品名称', max_length=128, verbose_name='产品名称')),
                ('prov_name', models.CharField(help_text='运营省份', max_length=64, verbose_name='运营省份')),
                ('prov_type', models.CharField(help_text='省份类型', max_length=64, verbose_name='省份类型')),
                ('prov_flag', models.CharField(help_text='省份推广状况', max_length=20, verbose_name='省份推广状况')),
                ('flag_update_time', models.CharField(help_text='省份推广状况更新时间', max_length=20, verbose_name='更新时间')),
                ('milepost_desc', models.CharField(blank=True, help_text='里程碑描述', max_length=1024, null=True, verbose_name='里程碑描述')),
                ('milepost_date', models.CharField(blank=True, help_text='里程碑日期', max_length=20, null=True, verbose_name='里程碑日期')),
                ('notes', models.CharField(blank=True, help_text='说明', max_length=256, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '运营数据视图信息表',
                'verbose_name_plural': '运营数据视图信息表',
                'db_table': 't_test_operate_view_info',
            },
        ),
        migrations.CreateModel(
            name='TTestRecordDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('cur_month', models.CharField(help_text='当月测试次数', max_length=30, verbose_name='当月测试次数')),
                ('use_times', models.CharField(help_text='接口使用次数', max_length=30, verbose_name='接口使用次数')),
            ],
            options={
                'verbose_name': '测试次数记录信息表',
                'verbose_name_plural': '测试次数记录信息表',
                'db_table': 't_test_record_data_info',
            },
        ),
    ]
